# Generated by Django 4.1 on 2022-08-04 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=300)),
                ('sana', models.DateField(auto_now_add=True)),
                ('asosiy_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Xabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaxt', models.DateTimeField()),
                ('matn', models.CharField(max_length=200)),
                ('jonatuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jonatuvchi_xabar', to='userapp.profil')),
                ('qabul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qabul_xabar', to='userapp.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Reaktisya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaktsiya', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profil')),
                ('xabar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.xabar')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(blank=True, max_length=200)),
                ('vaqt', models.DateField(auto_now_add=True)),
                ('joy', models.CharField(max_length=200)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postegi_rasimlar', to='asosiy.post')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likar', to='asosiy.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_liklar', to='userapp.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_liklar', to='asosiy.comment')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profil')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='asosiy.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profil'),
        ),
    ]
